
name: Test contracts

on:
  workflow_dispatch:
  pull_request:
   types: [opened, synchronize, reopened, ready_for_review]
  push:
   branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test-all
