
name: Contracts AutoTest

on:
  workflow_dispatch:
  pull_request:
   types: [labeled]
  push:
   branches:
    - main

jobs:
  build:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test-all
